
CREATE TABLE IF NOT EXISTS Users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Routes (
    RouteID INTEGER PRIMARY KEY AUTOINCREMENT,
    RouteName VARCHAR(255),
    StartPoint VARCHAR(255),
    EndPoint VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Buses (
    BusID INTEGER PRIMARY KEY AUTOINCREMENT,
    BusNumber VARCHAR(50),
    Capacity INT,
    RouteID INT,
    FOREIGN KEY (RouteID) REFERENCES Routes(RouteID)
);

CREATE TABLE IF NOT EXISTS Students (
    StudentID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) NOT NULL,
    Grade VARCHAR(50) NOT NULL,
    BusRouteId INT NOT NULL,
    BoardingPoint VARCHAR(255) NOT NULL,
    FOREIGN KEY (BusRouteId) REFERENCES Routes(RouteID)
);

CREATE TABLE IF NOT EXISTS Drivers (
    DriverID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255),
    LicenseNumber VARCHAR(50),
    Phone VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS MaintenanceLogs (
    LogID INTEGER PRIMARY KEY AUTOINCREMENT,
    BusID INT,
    Description TEXT,
    Date DATE,
    FOREIGN KEY (BusID) REFERENCES Buses(BusID)
);

CREATE TABLE IF NOT EXISTS Incidents (
    IncidentID INTEGER PRIMARY KEY AUTOINCREMENT,
    BusID INT,
    Description TEXT,
    Date DATE,
    FOREIGN KEY (BusID) REFERENCES Buses(BusID)
);
