CREATE DATABASE IF NOT EXISTS bus_fms;
USE bus_fms;

CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Routes (
    RouteID INT AUTO_INCREMENT PRIMARY KEY,
    RouteName VARCHAR(255),
    StartPoint VARCHAR(255),
    EndPoint VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Buses (
    BusID INT AUTO_INCREMENT PRIMARY KEY,
    BusNumber VARCHAR(50),
    Capacity INT,
    RouteID INT,
    FOREIGN KEY (RouteID) REFERENCES Routes(RouteID)
);

CREATE TABLE IF NOT EXISTS Students (
    StudentID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Grade VARCHAR(50) NOT NULL,
    BusRouteId INT NOT NULL,
    BoardingPoint VARCHAR(255) NOT NULL,
    FOREIGN KEY (BusRouteId) REFERENCES Routes(RouteID)
);

CREATE TABLE IF NOT EXISTS Drivers (
    DriverID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    LicenseNumber VARCHAR(50),
    Phone VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS MaintenanceLogs (
    LogID INT AUTO_INCREMENT PRIMARY KEY,
    BusID INT,
    Description TEXT,
    Date DATE,
    FOREIGN KEY (BusID) REFERENCES Buses(BusID)
);

CREATE TABLE IF NOT EXISTS Incidents (
    IncidentID INT AUTO_INCREMENT PRIMARY KEY,
    BusID INT,
    Description TEXT,
    Date DATE,
    FOREIGN KEY (BusID) REFERENCES Buses(BusID)
);
